spring:
  application:
    name: the-labot-backend

  datasource:
    url: jdbc:mysql://localhost:3306/local-test-db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #배포 시에는 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
