spring:
  profiles:
    active: local
  application:
    name: the-labot-backend

  jpa:
    hibernate:
      ddl-auto: update #배포 시에는 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Jwt 토큰
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}