spring:
  datasource:
    url: jdbc:mysql://db:3306/the_labot?serverTimezone=Asia/Seoul
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none #처음 한번만? none으로 하면 자동으로 db생성 안해줌 #create해야 스키마 변경했을때도 적용됨 (재부팅 하면서 drop-create)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      credentials:
        access-key: ${IAM_ACCESS_KEY}
        secret-key: ${IAM_SECRET_KEY}
      region:
        static: "ap-northeast-2" # 서울 리전
      s3:
        bucket: ${S3_BUCKET_NAME}

  #파일 업로드 용량 늘려주기 (기본은 1MB)
  servlet:
    multipart:
      max-file-size: 20MB #보내는거 파일 하나당
      max-request-size: 20MB # 한번 총 요청하는 최대 크기

ncp:
  ocr:
    invoke:
      url: ${NCP_OCR_INVOKE_URL}
    secret:
      key: ${NCP_OCR_SECRET_KEY}
    idcard:
      invoke:
        url: ${NCP_OCR_IDCARD_URL}
      secret:
        key: ${NCP_OCR_IDCARD_KEY}

solapi:
  api-key: ${SOLAPI_API_KEY}
  api-secret: ${SOLAPI_API_SECRET}
  sender-number: ${SOLAPI_SENDER_NUMBER}
  api-url: ${SOLAPI_API_URL}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
